package selenium;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;


import java.util.Properties;
import java.io.FileInputStream;

public class SeleniumTC06 {
	private WebDriver driver;
	private String baseUrl;
	private boolean acceptNextAlert = true;
	private StringBuffer verificationErrors = new StringBuffer();
	public Properties prop;
	public static String sAppURL, sSharedUIMapPath;

	@Before
	public void setUp() throws Exception {
		System.setProperty("webdriver.firefox.marionette", "C:\\GeckoSelenium\\geckodriver.exe");
		driver = new FirefoxDriver();
		baseUrl = "http://localhost:8080";
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		prop = new Properties();
		prop.load(new FileInputStream("./Configuration/ASAP_Configurations.properties"));
		sAppURL = prop.getProperty("sAppURL");
		sSharedUIMapPath = prop.getProperty("sSharedUIMap");
		prop.load(new FileInputStream(sSharedUIMapPath));

	}

	@Test
	public void testSeleniumTC06() throws Exception {
		driver.get(sAppURL);
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("UTA ID cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID_Error"))).getAttribute("value"));
		assertEquals("Username cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername_Error"))).getAttribute("value"));
		assertEquals("Password cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword_Error"))).getAttribute("value"));
		assertEquals("First Name cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname_Error"))).getAttribute("value"));
		assertEquals("Last Name cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname_Error"))).getAttribute("value"));
		assertEquals("Email cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Age cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age_Error"))).getAttribute("value"));
		assertEquals("Phone no. cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone_Error"))).getAttribute("value"));
		assertEquals("LicNo cannot be blank.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo_Error"))).getAttribute("value"));
		assertEquals("License expiry date cannot be empty", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("100158376A");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Your UTA ID must be a number", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("111");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Your UTA Id must be 10 digits long.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wa");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Your username must be atleast 5 in length.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasi");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Your username must be atleast 5 in length.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi12ipsokiedjiieiie");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Your username must be atleast 5 in length.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Te@1");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Te@1");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Password should be less than 15 and more than 8 characters in length.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword_Error"))).getAttribute("value"));

		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("Wasiq@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Wasiq@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Wasiq@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Password Should not be same as user name", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Password should contain atleast one upper case alphabet", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("TEST@345");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("TEST@345");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Password should contain atleast one lower case alphabet", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Testatmo@");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Testatmo@");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Password should contain atleast one number.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test123456");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test123456");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Password should contain atleast one special character", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("W");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Your First Name must be atleast 2 in length and atmost 25.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("A");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Your Last Name must be atleast 2 in length and atmost 25.", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("w@.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Email address must be between 7 and 45 characters long", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiqali.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Email address needs to contain @", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiqali@.wth");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Invalid domain name", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("682682");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Phone number must be 10 digits in length", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("571599670A");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Phone number must be a number", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone_Error"))).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TXA");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Invalid State Format", driver.findElement(By.name("stateerror")).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("7601354");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Zipcode should be exactly 5 in length.", driver.findElement(By.name("zipcodeerror")).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("7601A");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Zipcode must be a number", driver.findElement(By.name("zipcodeerror")).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("Arlington55wpeoirjiujhujhytagetdughjuhyiuyehiuyhi eehhhkjhkjdhkjashdkjashdjksadhsa");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Invalid Address Format", driver.findElement(By.name("addresserror")).getAttribute("value"));
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("15");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();
		assertEquals("Age cannot be less than 18", driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age_Error"))).getAttribute("value"));
		driver.get(baseUrl + "/ASAPCarRental/");
		new Select(driver.findElement(By.id(prop.getProperty("Slct_ASAPCarRental_UserType")))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_GenderMale"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name(prop.getProperty("Radio_ASAPCarRental_AACTrue"))).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();



		new Select(driver.findElement(By.id("userType"))).selectByVisibleText("User");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_UTAID"))).sendKeys("1001583762");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Firstname"))).sendKeys("Wasiq");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Lastname"))).sendKeys("Abbasi");
		driver.findElement(By.name("male")).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Email"))).sendKeys("wasiq.ali.zia@gmail.com");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegUsername"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_RegPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_ConfirmPassword"))).sendKeys("Test@123");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Age"))).sendKeys("28");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Phone"))).sendKeys("5715996701");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Address"))).sendKeys("1008 Greek Row Dr, Apt 221");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_State"))).sendKeys("TX");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Zipcode"))).sendKeys("76013");
		driver.findElement(By.name("aacTrue")).click();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicNo"))).sendKeys("123456789");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_LicExp"))).sendKeys("10/25/2020");
		driver.findElement(By.xpath(prop.getProperty("Btn_ASAPCarRental_Register"))).click();




		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Username"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Username"))).sendKeys("wasiqaliabbasi6");
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Password"))).clear();
		driver.findElement(By.name(prop.getProperty("Txt_ASAPCarRental_Password"))).sendKeys("Test@123");
		driver.findElement(By.cssSelector(prop.getProperty("Btn_ASAPCarRental_Login"))).click();
		assertTrue(isElementPresent(By.linkText(prop.getProperty("Link_ASAPCarRental_Logout"))));
		driver.findElement(By.linkText(prop.getProperty("Link_ASAPCarRental_Logout"))).click();
	}

	@After
	public void tearDown() throws Exception {
		driver.quit();
		String verificationErrorString = verificationErrors.toString();
		if (!"".equals(verificationErrorString)) {
			fail(verificationErrorString);
		}
	}

	private boolean isElementPresent(By by) {
		try {
			driver.findElement(by);
			return true;
		} catch (NoSuchElementException e) {
			return false;
		}
	}

	private boolean isAlertPresent() {
		try {
			driver.switchTo().alert();
			return true;
		} catch (NoAlertPresentException e) {
			return false;
		}
	}

	private String closeAlertAndGetItsText() {
		try {
			Alert alert = driver.switchTo().alert();
			String alertText = alert.getText();
			if (acceptNextAlert) {
				alert.accept();
			} else {
				alert.dismiss();
			}
			return alertText;
		} finally {
			acceptNextAlert = true;
		}
	}
}
